import { existsSync, readFileSync } from "node:fs";
import { webcrypto } from "node:crypto";
import { join } from "node:path";

import { beforeAll, describe, expect, it } from "vitest";

import { UNKNOWN_COUNTRY } from "@creator-map/shared-schemas";

import {
  creatorPageCount,
  loadActiveRelease,
  loadCountryDetail,
  loadCreatorPage,
} from "./loader";

/**
 * The cross-stack contract, checked against a deterministic fixture.
 *
 * `real-artifacts.test.ts` reads `dist/`, which is the strongest check
 * available — real bytes, real generator — but it skips when no release
 * has been built. That means a clean checkout and any CI job without a
 * database run it and prove nothing, while still reporting green.
 *
 * This reads `fixtures/dist/`, generated by
 * `python -m creator_map_pipeline.cli_fixture` with no database and no
 * network. Same generator code path, same digests, same loader. If the
 * Python writer and the TypeScript reader disagree about paths, digests,
 * or shapes, it fails here rather than in a browser.
 *
 * The fixture is checked in, so a drift introduced on the Python side
 * without regenerating it also fails here — which is the point. Nothing
 * in it describes a real creator.
 *
 * Requirement refs: 8.1, 8.8, 14.6-14.11
 */

const FIXTURES = join(process.cwd(), "fixtures", "dist");

beforeAll(() => {
  if (!globalThis.crypto?.subtle) {
    Object.defineProperty(globalThis, "crypto", { value: webcrypto });
  }
});

function fileFetch(root: string = FIXTURES): typeof fetch {
  const impl = (path: string) => {
    const target = join(root, path);
    if (!existsSync(target)) {
      return Promise.resolve({
        ok: false,
        status: 404,
        arrayBuffer: () => Promise.resolve(new ArrayBuffer(0)),
      });
    }
    const buffer = readFileSync(target);
    return Promise.resolve({
      ok: true,
      status: 200,
      arrayBuffer: () =>
        Promise.resolve(
          buffer.buffer.slice(
            buffer.byteOffset,
            buffer.byteOffset + buffer.byteLength,
          ),
        ),
    });
  };
  return impl as unknown as typeof fetch;
}

describe("the checked-in fixture release", () => {
  it("exists, so this suite never silently skips", () => {
    // The failure this whole file guards against is a contract test that
    // reports green because it ran nothing.
    expect(existsSync(join(FIXTURES, "active-release.json"))).toBe(true);
  });

  it("loads through the full verified chain", async () => {
    const release = await loadActiveRelease({ fetchImpl: fileFetch() });

    expect(release.manifest.releaseId).toBe(release.pointer.releaseId);
    expect(release.overview.releaseId).toBe(release.manifest.releaseId);
    expect(release.manifest.datasets.length).toBeGreaterThan(0);
  });

  it("passes digest verification on every artifact it serves", async () => {
    // The loader verifies before parsing. If Python's canonical
    // serialization and the TypeScript digest check ever diverge, every
    // one of these throws.
    const release = await loadActiveRelease({ fetchImpl: fileFetch() });

    for (const summary of release.overview.countries) {
      const detail = await loadCountryDetail(
        release.manifest,
        summary.country,
        {
          fetchImpl: fileFetch(),
        },
      );
      expect(detail.country).toBe(summary.country);
    }
  });

  it("has a coverage partition that reconciles", async () => {
    const { overview } = await loadActiveRelease({ fetchImpl: fileFetch() });
    const { coverage } = overview;
    const partitionTotal = Object.values(coverage.partition).reduce(
      (sum, value) => sum + value,
      0,
    );

    expect(partitionTotal).toBe(coverage.distinctInputVideoCount);
  });

  it("splits channel coverage exactly", async () => {
    const { overview } = await loadActiveRelease({ fetchImpl: fileFetch() });
    const { coverage } = overview;

    expect(
      coverage.knownCountryChannelCount + coverage.unknownCountryChannelCount,
    ).toBe(coverage.resolvedChannelCount);
  });

  it("reports more occurrences than distinct videos", async () => {
    // A distinct video count above the occurrence count is impossible:
    // every distinct video is backed by at least one occurrence.
    const { overview } = await loadActiveRelease({ fetchImpl: fileFetch() });

    expect(overview.coverage.inputOccurrenceCount).toBeGreaterThanOrEqual(
      overview.coverage.distinctInputVideoCount,
    );
  });

  it("carries an Unknown country bucket", async () => {
    // Unknown is a real category, not an absence. Dropping it would make
    // the country subtotals look like the whole corpus.
    //
    // Compared against the exported constant rather than a literal: the
    // bucket is "XX" (user-assigned in ISO 3166, so it cannot collide
    // with a real country), and a hardcoded "Unknown" here would pass
    // only by accident.
    const { overview } = await loadActiveRelease({ fetchImpl: fileFetch() });

    expect(overview.countries.some((c) => c.country === UNKNOWN_COUNTRY)).toBe(
      true,
    );
  });

  it("never advertises a page it does not publish", async () => {
    // The defect this catches shipped once: pagination advertised 2,747
    // rows and published 50, so a cursor 404ed mid-traversal.
    const release = await loadActiveRelease({ fetchImpl: fileFetch() });

    for (const summary of release.overview.countries) {
      const detail = await loadCountryDetail(
        release.manifest,
        summary.country,
        {
          fetchImpl: fileFetch(),
        },
      );
      const pages = creatorPageCount(detail, "representedVideoCountDesc");

      for (let page = 0; page < pages; page += 1) {
        const loaded = await loadCreatorPage(
          release.manifest,
          detail,
          "representedVideoCountDesc",
          page,
          { fetchImpl: fileFetch() },
        );
        expect(loaded.rows.length).toBeGreaterThan(0);
      }
    }
  });

  it("publishes every counted creator across its pages", async () => {
    const release = await loadActiveRelease({ fetchImpl: fileFetch() });

    for (const summary of release.overview.countries) {
      const detail = await loadCountryDetail(
        release.manifest,
        summary.country,
        {
          fetchImpl: fileFetch(),
        },
      );

      expect(detail.firstPage.totalRows).toBe(summary.creatorCount);
    }
  });

  it("orders creator rows the way it claims to", async () => {
    const release = await loadActiveRelease({ fetchImpl: fileFetch() });
    const detail = await loadCountryDetail(release.manifest, "US", {
      fetchImpl: fileFetch(),
    });

    const counts = detail.firstPage.rows.map((r) => r.representedVideoCount);
    expect([...counts].sort((a, b) => b - a)).toEqual(counts);
  });

  it("exposes no raw channel identifier", async () => {
    // Public keys are HMAC-derived. A raw 24-character channel id in a
    // published artifact is the disclosure failure the boundary exists
    // to prevent.
    const release = await loadActiveRelease({ fetchImpl: fileFetch() });
    const detail = await loadCountryDetail(release.manifest, "ZA", {
      fetchImpl: fileFetch(),
    });

    for (const row of detail.firstPage.rows) {
      expect(row.publicChannelKey).toMatch(/^pk_/);
      expect(row.publicChannelKey).not.toMatch(/^UC[\w-]{22}$/);
    }
  });

  it("fails closed on a corrupted artifact", async () => {
    // Requirement 14.7: a digest mismatch must not render as data.
    const release = await loadActiveRelease({ fetchImpl: fileFetch() });
    const corrupting = (() => {
      const impl = (path: string) => {
        if (path.includes("countries/US.json")) {
          const tampered = new TextEncoder().encode('{"country":"US"}');
          return Promise.resolve({
            ok: true,
            status: 200,
            arrayBuffer: () => Promise.resolve(tampered.buffer),
          });
        }
        return (fileFetch() as unknown as (p: string) => unknown)(path);
      };
      return impl as unknown as typeof fetch;
    })();

    await expect(
      loadCountryDetail(release.manifest, "US", { fetchImpl: corrupting }),
    ).rejects.toThrow();
  });
});
